# Generated by Django 4.2.11 on 2026-06-10 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PROJECT", "Project Report"),
                            ("TASK", "Task Report"),
                            ("EMPLOYEE", "Employee Report"),
                            ("TEAM", "Team Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(default=dict)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
