# Generated by Django 4.2.11 on 2026-06-10 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_UPDATED", "Task Updated"),
                            ("TASK_COMPLETED", "Task Completed"),
                            ("DEADLINE_REMINDER", "Deadline Reminder"),
                            ("PROJECT_UPDATED", "Project Updated"),
                            ("FILE_UPLOADED", "File Uploaded"),
                            ("TEAM_MESSAGE", "Team Message"),
                            ("COMMENT_ADDED", "Comment Added"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
